apiVersion: v1
kind: Service
metadata:
  name: {{ service_name }}-nodeport-service
  namespace: {{ squad_name }}
  labels:
    app: {{ service_name }}
spec:
  type: NodePort
  selector:
    app: {{ service_name }}
  ports:
    - port: {{ container_port }}
      targetPort:  {{ container_port }}
